### PR TITLE
Added a button for users to update their ssh key

### PR DESCRIPTION
**Pull request by tefarley**

### CODE REVIEW

**Review by jSylvestre — CHANGES_REQUESTED** [review]
If it is an internal link, I believe there is a Link tsx.
Anyway, having the hard coded hostname is bad.

**Comment by sprucely** [comment]
`<NavLink />` is what you're looking for.
https://github.com/ucdavis/hippo/blob/5a21ab2d07727f34b503a46284accc71733345eb/Hippo.Web/ClientApp/src/AppNav.tsx#L39-L48

**Comment by tefarley** [comment]
Who wrote this crap? Oh wait.. ;) I faintly remember trying the navlink before, but the <Link> from router dom is interesting I thought that was only added in Next.js . I'll make some changes

**Comment by jSylvestre** [comment]
I see you have a nullable on the match? Perhaps just hide this if that is null?

**Comment by tefarley** [comment]
I think I accidentally left that in there ty. I can't think hippo rn, where can I get cluster name from in AccountInfo?

**Comment by tefarley** [comment]
nvm ty

**Comment by tefarley** [comment]
Yes ty a nullable match is not great. I can't think hippo well atm where can I get cluster.name from?

**Pull request closed without merging**
